### ISSUE TITLE
Improvements to CoreModel

### ISSUE THREAD

**Issue by gemcoder21** [keepwallet/keep-core#1]
- [x] Remove `Measure` and put inside `Asset`
 - [x] Remove `shared` framework
-  [x] Rename `Coin` to `Chain`
- [ ] Implement proper `enum` for Swift
- [ ] Capitalise Asset name from `ETHEREUM` to `Ethereum`
- [ ] Rename `Asset.Address` to `Asset.ID` or something similar
- [ ] Make `getTokenStandard` not throwable? so there is always something
- [ ] Clean up `Coin` list and only keep chains that would be implemented

**Comment by riatoshi** [comment]
> Remove Measure and put inside Asset

Why?
