### ISSUE TITLE
Structure of Core Libs

### ISSUE THREAD

**Issue by gemcoder21** [keepwallet/keep-core#4]
# Core Libs

## CoreModel
- Basic models (Wallet, Account, Ticker)

## CoreCrypto
- Wallets Management
- Signer (transactions signer). Do we need to bring WalletCore here?

## CoreBlockchains

- Balances Provider
- Transactions Provider
- Broadcast Transactions Provider

**Comment by riatoshi** [comment]
> Signer (transactions signer). Do we need to bring WalletCore here?

Noup
